### ISSUE TITLE
Unexpected token ?

### ISSUE THREAD

**Issue by xlingdev** [PrismarineJS/node-yggdrasil#63]
```js
/home/fedora/accsharebot/node_modules/yggdrasil/lib/Client.js:37
            options.token = options.token ?? uuid_1.default.v4();
                                           ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:1070:16)
    at Module._compile (internal/modules/cjs/loader.js:1120:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/fedora/accsharebot/node_modules/yggdrasil/lib/index.js:5:34)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
```

**Comment by rom1504** [comment]
update your node

we need to add the same as https://github.com/PrismarineJS/mineflayer/blob/master/index.js#L1

**Comment by Omnius1234** [comment]
how to fix ???

**Comment by Moondarker** [comment]
You've got to be trolling, @Omnius1234
